version: "3"

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rw
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: rush
      MYSQL_USER: joshua
      MYSQL_PASSOWRD: abc123
      MYSQL_ROOT_PASSWORD: abcd123
      SERVICE_TAGS: dev
      SERVINCE_NAME: mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
  composer:
    image: composer:latest
    container_name: composer
    restart: unless-stopped
    command: ["composer", "install"]
    volumes:
      - ./src:/app
    depends_on:
      - php
    networks:
      - laravel
